### ISSUE TITLE
Sample CV no longer scans through waves in folder in v.1.0.6

### ISSUE THREAD

**Issue by Petervos2018** [LomasModules/LomasModules#7] opened 2019-09-02 16:31 UTC
No matter what voltage the sample will not change.
The sample knob works but I can not change it with cv.

Greetings Peter.

**Comment by espenstoro** [comment] 2019-09-02 17:23
Came here to say this.

**Comment by LomasModules** [comment] 2019-09-02 21:07
Thanks for the feedback. It is fixed now.

You can download a windows version here:
https://github.com/LomasModules/LomasModules/releases/tag/v1.0.7

I will wait a couple of days before sending it to the module library.

**Comment by Petervos2018** [comment] 2019-09-03 16:22
Ok 1.0.7 scans through the folder but,
now I have all kinds of clicks and some sort of DC offset pulses, it's just not usable for me on W7.
I don't know how to give you more info but this does not work for me.
On the upside 1.0.2 works flawless but I read somewhere that the interpolation did nothing. ?
How can I help you to fix this ?

Greetings Peter.

**Comment by LomasModules** [comment] 2019-09-03 17:05
Could you give me more details on how to reproduce the bug?
What size are the files your are playing? Do you change samples really fast? Do you use a hdd or a sdd? Doe the module use too much CPU? 

It may be because now the sampler don't load samples before using them. Try to move the sample knob from start to end. That will load all the samplers on the folder. I changed it because opening folders with too many files crashed rack.

**Comment by Petervos2018** [comment] 2019-09-03 17:24
I'm on an ssd , tried to move the sample knob from start to end but that didn't do anything.
Here is a project including the samples.
Load the project choose the sample folder hit "run" and listen.
The volume on the mixer is way down low but you hear a click with every trigger !

[DrumLomas Test Clicks - 03092019.zip](https://github.com/LomasModules/LomasModules/files/3570666/DrumLomas.Test.Clicks.-.03092019.zip)

Hope this helps a bit,
Greets Peter.

**Comment by LomasModules** [comment] 2019-09-03 17:55
I don't think is the sampler.
I loaded the patch and herad the clicks. I conected the output of the sampler directly to the audio-8 and seems to sound fine.

**Comment by Petervos2018** [comment] 2019-09-03 18:04
But look at the signal coming from the DC blocker there is something strange going on here....
1.0.2. does not give me these strange signals....
Or use audio out to bogaudio XL and you see shapes you never seen before..

**Comment by LomasModules** [comment] 2019-09-03 18:46
Now I know what you mean. I will have to investigate further.

I don't really understand why this happens. A simple filter on the output will get rid of the problem. But I would like to know why it happens. Can you explain to me what the patch does?

**Comment by Petervos2018** [comment] 2019-09-03 19:03
Sorry you lost me there ... most of the stuff in the patch is just trying to visualize why I hear what I hear.
Basically the patch is just your sampler playing a folder with samples in a random order...
Nysti's DC is a DC blocker but it gets hit with some strange offset and it should just filter out the extreme lows from the signal but it seems not to be able to.

**Comment by LomasModules** [comment] 2019-09-03 19:09
I dont use ML or Geodesic modules. I understand it now. Thanks I will look into it.

**Comment by Petervos2018** [comment] 2019-09-03 19:14
Oh... ML Triggerbuffer is making sure that the sample only plays after it is finished, so when a trigger is coming while the sample is playing it won't be triggered. And Branes is just a noise generator with sample and hold, in this case 0-10V.

**Closed as completed** 2019-11-27 20:16 UTC
Labels: bug
